name: Upload Node.js App to Artifactory

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the appropriate Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Create the package (tarball)
      - name: Create tarball
        run: |
          npm pack
          
      # Set up JFrog CLI for Artifactory interaction
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/

      # Configure JFrog CLI with Artifactory credentials
      - name: JFrog CLI Configuration
        run: |
          jfrog rt config --url ${{ secrets.ARTIFACTORY_URL }} --user ${{ secrets.ARTIFACTORY_USER }} --password ${{ secrets.ARTIFACTORY_API_KEY }}
        
      # Upload the package to Artifactory
      - name: Upload package to Artifactory
        run: |
          jfrog rt upload "nodejs-artifact-test-1.0.0.tgz" npm-repo/my-node-app/1.0.0/

      # Trigger Xray scan on the uploaded artifact
      - name: Trigger Xray Scan
        run: |
          jfrog rt xray "npm-repo/my-node-app/1.0.0/nodejs-artifact-test-1.0.0.tgz"

      # Display scan results (optional)
      - name: Display Xray Scan Results
        run: |
          jfrog rt xray "npm-repo/my-node-app/1.0.0/nodejs-artifact-test-1.0.0.tgz" --status
